apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator
  namespace: trivy-system
data:
  trivy.serverInsecure: "false"
  trivy.severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  trivy.vulnerabilityReports.scanScope: workload
  trivy.vulnerabilityReports.scanJobTimeout: 5m
  trivy.vulnerabilityReports.scanJobsInParallel: 3
  # Scan only the aaks namespace
  trivy.namespaceAsSbomInputNamespaces: aaks
