apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Trivy Operator installation (helm-less via kustomize)
  # Pinned to v0.20.0 - update via bump in comments
  - github.com/aquasecurity/trivy-operator deployments/kubernetes kustomize/overrides
  - config.yaml
