apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # External Secrets Operator installation
  # Pinned to v0.11.0 - update via bump in comments
  - github.com/external-secrets/external-secrets manifests/deploy/crds
  - github.com/external-secrets/external-secrets manifests/deploy/rbac
  - github.com/external-secrets/external-secrets manifests/deploy/overlays/namespace-scoped
  - externalsecret-aaks.yaml
