apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - verify-images.yaml
  - disallow-latest.yaml
  - require-non-root.yaml
  - require-resource-limits.yaml
  - restrict-privileged.yaml
  - restrict-hostpath.yaml
